baseURL: "/"
enableRobotsTXT: True
languageCode: "en-us"
title: "Upbound Docs"
theme: "upbound"
enableGitInfo: true
uglyurls: false
timeout: 180000
disableKinds:
  - taxonomy
  - term
  - RSS

build:
  # writeStats: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
  highlight:
    codeFences: true
    noClasses: false
    linenos: false
    anchorLineNos: true
    lineNumbersInTable: false

module:
  mounts:
  - source: content
    target: content
  - source: assets
    target: assets
  - source: content
    target: assets/content
    includeFiles:
      - "**/**.png"
      - "**/**.jpg"
      - "**/**.jpeg"
      - "**/**.gif"
  - source: content
    target: data/crds
    includeFiles:
      - "**/**.yaml"

# Enable Hugo access to environmental variables to apply deploy preview banner
security:
  funcs:
    getenv:
      - ^CONTEXT
      - ^REVIEW_ID

params:
  latest: v1.10   #we should look to replace this value with the spaces.version values below
  repoLink: "https://github.com/upbound/"
  anchors:
    min: 2
    max: 5
  description: "Crossplane lets you build a control plane with Kubernetes-style declarative and API-driven configuration and management for anything."

  hideDropdown:
    - "reference/space-api"
  spaces:
    version:
      major: 1
      minor: 10
      patch: 0
