description: |-
    Type of row condition. The only defined value is 'Completed' indicating that the
    object this row represents has reached a completed state and may be given less visual
    priority than other rows. Clients are not required to honor any conditions but should
    be consistent where possible about handling the conditions.