description: |-
    format is an optional OpenAPI type modifier for this column. A format modifies the type and
    imposes additional rules, like date or time formatting for a string. The 'name' format is applied
    to the primary identifier column which has type 'string' to assist in clients identifying column
    is the resource name.
    See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for more.