description: |-
    type is an OpenAPI type definition for this column, such as number, integer, string, or
    array.
    See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for more.