cli:
  - adamwg
  - sttts
  - RedbackThomson
  - tnthornton
  - phisco
  - turkenh
  - haarchri
console:
  - thephred
  - adamwg
  - miloszsobczak
  - jastang Maintainer
  - nullable-eth
  - julzvilla
  - haarchri
ctps:
  - jeanduplessis
  - luxas
  - phisco
  - ulucinar
  - turkenh
  - ezgidemirel
  - sergenyalcin
  - lsviben
  - turkenf
  - erhancagirici
cloud:
  - branden
  - avalanche123
  - risingspiral
  - RedbackThomson
  - tnthornton
  - cbuto
extensions:
  - jeanduplessis Maintainer
  - ulucinar
  - sergenyalcin
  - turkenf

